/**
 * The 68 famous figures in CURATED POWER ORDER (rank 1 = most powerful).
 * Order and spelling preserved exactly as specified, INCLUDING the
 * "Georgep Gervin" typo (intentional — flagged to user, not silently fixed).
 * Inner quotes use single quotes so strings can live in double-quoted
 * TS literals without escaping; curly apostrophes converted to straight '.
 */
export const NAMES: readonly string[] = [
  "Zeus",
  "Michael Jordan",
  "Walter White",
  "Charlie Bucket",
  "Denzel Washington",
  "Shaquille O'Neal",
  "Allen 'The Answer' Iverson",
  "Bruce Wayne",
  "Blade",
  "Apollo Creed",
  "Kobe Bryant",
  "L Lawliet",
  "Bruce Lee",
  "Gene Wilder",
  "Samuel L. Jackson",
  "Hakeem Olajuwon",
  "Earvin 'Magic' Johnson",
  "Peter Parker",
  "Morpheus",
  "Muhammad Ali",
  "Kevin Durant",
  "Lelouch Lamperouge",
  "James Bond",
  "Giancarlo Esposito",
  "Wilt Chamberlain",
  "Julius 'Dr. J' Erving",
  "T'Challa",
  "John Wick",
  "Nicolas Cage",
  "Lucifer Morningstar",
  "God",
  "LeBron James",
  "Light Yagami",
  "Willy Wonka",
  "Don Cheadle",
  "Kareem A. Jabbar",
  "Pete 'Pistol' Maravich",
  "Tony Stark",
  "Wesley Snipes",
  "Odin",
  "Kawhi Leonard",
  "Gus Fring",
  "Maximus Decimus Meridius",
  "Idris Elba",
  "Moses Malone",
  "Clyde 'The Glide' Drexler",
  "Clark Kent",
  "Alucard",
  "Clubber Lang",
  "Tracy McGrady",
  "Johan Liebert",
  "Ip Man",
  "Christopher Walken",
  "Mahershala Ali",
  "David Robinson",
  "Dominique 'The Human Highlight Film' Wilkins",
  "Erik Killmonger",
  "Vincent Vega",
  "Laurence Fishburne",
  "Hades",
  "Damian Lillard",
  "Spike Spiegel",
  "Thomas Shelby",
  "Keith David",
  "Georgep Gervin",
  "Paul 'The Truth' Pierce",
  "Miles Morales",
  "Frank Castle",
] as const;

export const NAME_COUNT = NAMES.length; // 68
